		<div id="filters">
			<div id="filter_instructions_lol">Use these filters to display the changelog you want</div>
			<div id="filter_options">
				<form name="filters" action="/changelog" method="post">
					<div style="float: left;" class="input">
						<label for="nickname">Nickname</label>
						<input type="text" name="byplayernickname" value="<?=$param['byplayernickname'];?>">
					</div>

					<div style="float: left;" class="input">
						<label for="profilenumber">Steam profile number</label>
						<input type="text" name="byplayer_steamid" value="<?=$param['byplayer_steamid'];?>">
					</div>

                    <div style="float: left;" class="input">
                        <label for="profilenumber">Chapter name</label>
                        <select style="width: 100%;" name="bychapter_name">
                            <option value="">No chapter</option>
                            <?php foreach(Leaderboard::getMaps() as $chapterName => $maps): ?>
                                <option value="<?=$chapterName?>"  <?php if($param['bychapter_name'] == $chapterName): ?>selected<?php endif; ?>><?=$chapterName?></option>
                            <?php endforeach; ?>
                        </select>
                    </div>

					<div style="float: left;" class="input">
						<label for="profilenumber">Map name</label>
                        <select style="width: 100%;" name="bychamber_name">
                            <option value="">No map</option>
                            <?php foreach(Leaderboard::getMaps() as $chapterName => $maps): ?>
                                <option disabled><?=$chapterName?></option>
                                <?php foreach($maps as $mapname): ?>
                                    <option value="<?=$mapname?>" <?php if($param['bychamber_name'] == $mapname): ?>selected<?php endif; ?>>&nbsp;&nbsp;<?=$mapname?></option>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </select>
					</div>

					<script type="text/javascript">
					$(document).ready(function() {
						$(".checkbox").click(function() {
							$(this).toggleClass("ticked");
							var v = $(this).parent().find("input:eq(0)").val();
							v = (v == 0 ? 1 : 0);
							$(this).parent().find("input:eq(0)").val(v);
						});
						function inputresize() {
							var troll = $("#filters").width() - 500;
							var troll = troll / 4;
							// my pro lazy javascript skills. pls dont judge me from this.
                            // 04.27.2014 wtf is this shit nuclear do you even CSS m8?
							$("input[type=text], select").attr("style", "width:"+troll+"px");
						}
						inputresize();
						$(window).resize(inputresize);

						$("#otherentries .entry:odd").attr("style", "background: #d3d3d3;");



					});
					</script>
					<div style="float: left;" class="check">
						<div style="position: relative; ">Singleplayer</div>
						<div class="checkbox <?php if($param['sp'] == "1"): ?>ticked<?php endif; ?>"></div>
						<input type="hidden" value="<?=$param['sp'];?>" name="sp">
					</div>
					<div style="float: left;" class="check">
						<div style="position: relative;">Cooperative</div>
						<div class="checkbox <?php if($param['coop'] == "1"): ?>ticked<?php endif; ?>"></div>
						<input type="hidden" value="<?=$param['coop'];?>" name="coop">
					</div>
					<div style="float: left;" class="check">
						<div style="position: relative;">World record</div>
						<div class="checkbox <?php if($param['wr'] == "1"): ?>ticked<?php endif; ?>"></div>
						<input type="hidden" value="<?=$param['wr'];?>" name="wr">
					</div>
					<div style="float: right; margin: 30px 20px 0px 0px">
						<input type="submit" value="Filter"></input>
					</div>
				</form>


			</div>
		</div>

		<div id="changelog">
			<div id="firstentry">
				<div class="time">Time</div>
				<div class="player">Player</div>
				<div class="map">Map</div>
				<div class="chapter">Chapter</div>
				<div class="newscore">New score</div>
				<div class="previousscore">Previous score</div>
				<div class="worldrecord">World Record</div>
			</div>
			<div id="otherentries">
				<?php foreach ($view->scoreUpdates as $key => $val): ?>
				<div class="entry">
					<div class="time"><?=$val["time_gained"]?></div>
					<div class="player"><a href="/profile/<?=$val["profile_number"]?>"><?=$val["player_name"]?></a></div>
					<div class="map"><a href="/chamber/<?=$val["mapid"]?>"><?=$val["name"]?></a></div>
					<div class="chapter"><?=$val["chapter_name"]?></div>
					<div class="newscore"><?=$val["score"]?> <?php if($val["improvement"] != null): ?><?="(".$val["improvement"].")";?><?php endif; ?></div>
					<div class="previousscore"><?=$val["previous_score"]?></div>
					<div class="worldrecord"><?php if($val["wr_gain"] == 1) { ?><div class="wr"></div><?php } ?></div>
				</div>
				<?php endforeach; ?>
			</div>
		</div>