		<?php
        $highlight = @$view->User->loggedInUser->board_nickname;
		$chapterNumber=1;foreach($view->board as $board_key => $board_val): ?>
			<div class="chapterinfo">
			<h1 class="chapternumber">Chapter 0<?php echo $chapterNumber;$chapterNumber++;?></h1>
			<h1 class="chaptername"><?=$board_key;?></h1>
			</div>
			<div class="chambers">
			<?php foreach($board_val as $chamb_key => $chamb_val): ?>


				<div class="chamber">
				<div class="chamberimage" style="background: url('/images/chambers/<?=$chamb_val[0][0];?>.jpg')">
					<div class="chambertitle">
						<div class="titlebghelper"></div>
						<div class="titlebg"><a href="/chamber/<?=$chamb_val[0][0];?>"><?=$chamb_key; ?></a></div>
						<div class="chamber_icons">
							<span class="icons youtube_icon"></span>
							<a href="<?php echo "http://steamcommunity.com/stats/Portal2/leaderboards/".$chamb_val[0][0]; ?>" class="icons steam_icon" target="_blank"></a>
						</div>
					</div>

				</div>
				<div class="chamber_scores">

												<?php if($chamb_val[1][0][1] == $chamb_val[1][1][1]) {
													$twoplayer_highlight = false;
													if($chamb_val[1][0][0] == $highlight || $chamb_val[1][1][0] == $highlight) {
														$twoplayer_highlight = true;
													}
													$chamb_val[1][0][0] .= " & ".$chamb_val[1][1][0];
													unset($chamb_val[1][1]);
												} 
												?>
												<?php $i = 0; ?>
												<?php foreach($chamb_val[1] as $pl_key => $pl_val): ?>
													<?php if($i < 8): ?>
														<?php if($pl_key == 0) { ?>
														<div class="firstplace">
															<div class="entry">
																<div class="name"><div class="twoplayers <?php if($twoplayer_highlight) {echo "highlight";}?>"><?=$pl_val[0]?></div></div>
																<div class="score"><?=$pl_val[1]?></div>
															</div>
														</div>
														<div class="othernoobscores">
														<?php } 
														else {
														?>
														<div class="entry <?php if($highlight == $pl_val[0]) { echo "highlight"; } ?>">
															<div class="name"><?=$pl_val[0]?></div>
															<div class="score"><?=$pl_val[1]?></div>
														</div>
														<?php } ?>
													<?php endif; ?>
													<?php $i++; ?>
												<?php endforeach; ?>
													</div>
												</div>
</div>
			<?php endforeach; ?>
		</div>
<?php endforeach; ?>