<!DOCTYPE>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <title><?php echo $view->siteTitle . $view->pageName; ?></title>
    <?php foreach($view->css as $path): ?>
        <link rel="stylesheet" type="text/css" href="<?=$path; ?>?v=<?=$view->browserCacheVersion; ?>">
    <?php endforeach; ?>

    <?php foreach($view->js as $path): ?>
        <script type="text/javascript" src="<?=$path; ?>"></script>
    <?php endforeach; ?>

    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-43126557-1']);
        _gaq.push(['_trackPageview']);
        (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
    </script>
    <script type="text/javascript">
        var _bftn_options = { animation: 'banner' }
    </script>
    <script src="//widget.battleforthenet.com/widget.min.js" async></script>
</head>

<body>
<div id="wrapper">
    <div id="header">
        <div id="header_left">
            <h2 id="sitetitle">Portal 2 Leaderboards</h2>
            <div id="navigation">
                <?php include("parts/navigation.phtml"); ?>
            </div>
        </div>

        <div id="header_right">
            <div id="userinfo">
                <?php include("parts/userinfo.phtml"); ?>
            </div>
        </div>
    </div>
    <?php include("parts/message.phtml"); ?>
    <div id="content">
        <?php
            if(isset($this->pages[$this->Page]["contentTemplate"])) {
                require_once($this->pages[$this->Page]["contentTemplate"]);
            }
        ?>
    </div>
    <div class="push"></div>
</div>

<?php include("parts/footer.phtml"); ?>
</body>

</html>