		<?php $content = $view->singlesegment; ?>
        <div class="col-2set singlesegment">
			<div class="col1">
				<div class="ss-wrapper">
					<div id="ss-p1">
						<div class="ss-info">
							<h1>Portal 1</h1>
							<?php foreach($content[0]["Portal 1"] as $category => $board): ?>
								<h2><?=$category;?></h2>
							<?php endforeach; ?>
							<div class="ss-controls">
								<?php $i = 0; ?>
								<?php foreach($content[0]["Portal 1"] as $category => $board): ?>
									<?php $i++; ?>
									<span <?php if($i == 1):?>class="active"<?php endif;?>><?=$i;?></span>
								<?php endforeach; ?>
							</div>
						</div>
					</div>
					<div class="ss-tables">
						<?php foreach($content[0]["Portal 1"] as $category => $board): ?>
						<div class="datatable">
							<div id="firstentry">
								<div class="player">Player(s)</div>
								<div class="time-noloads">Time without loads</div>
								<div class="time-withloads">Time with loads</div>
							</div>
							<div id="otherentries">
								<?php foreach($board as $entry => $entryData): ?>
								<div class="entry">
									<div class="player"><?=$entryData["Player"]?></div>
									<div class="time-noloads"><?=$entryData["Time(w/o Loads)"]?></div>
									<div class="time-withloads"><?=$entryData["Time(w/ Loads)"]?></div>
								</div>
								<?php endforeach; ?>
							</div>
						</div>
						<?php endforeach; ?>
					</div>
				</div>
			</div>
			<div class="col2">
				<div class="ss-wrapper">
					<div id="ss-p2">
						<div class="ss-info">
							<h1>Portal 2</h1>
							<?php foreach($content[0]["Portal 2"] as $category => $board): ?>
								<h2><?=$category;?></h2>
							<?php endforeach; ?>
							<div class="ss-controls">
								<?php $i = 0; ?>
								<?php foreach($content[0]["Portal 2"] as $category => $board): ?>
									<?php $i++; ?>
									<span <?php if($i == 1):?>class="active"<?php endif;?>><?=$i;?></span>
								<?php endforeach; ?>
							</div>
						</div>
					</div>
					<div class="ss-tables">
						<?php foreach($content[0]["Portal 2"] as $category => $board): ?>
						<div class="datatable">
							<div id="firstentry">
								<div class="player">Player(s)</div>
								<div class="time-noloads">Time without loads</div>
								<div class="time-withloads">Time with loads</div>
							</div>
							<div id="otherentries">
								<?php foreach($board as $entry => $entryData): ?>
								<div class="entry">
									<div class="player"><?=$entryData["Player"]?></div>
									<div class="time-noloads"><?=$entryData["Time(w/o Loads)"]?></div>
									<div class="time-withloads"><?=$entryData["Time(w/ Loads)"]?></div>
								</div>
								<?php endforeach; ?>
							</div>
						</div>
						<?php endforeach; ?>
					</div>
				</div>
			</div>
			<div class="ss-notice"><b>Notice:</b> this is a mirror of <a href="http://cronikeys.com/portal/index.php?title=Leaderboards">CRONIKEYS.COM Wiki "Leaderboard" page</a>. This page was last updated <?=$content[1];?></div>
		</div>
	<script type="text/javascript">
	$(document).ready(function() {
		$(".ss-controls span").click(function() {
			$(this).parent().find("span").removeClass("active");
			$(this).addClass("active");
			var btnIndex = $(this).index();
			var ssContainer = $(this).parent().parent();
			var ssWrapper = $(ssContainer).parent().parent();
			$(ssContainer).find("h2").hide();
			$(ssContainer).find("h2:eq("+btnIndex+")").show();
			$(ssWrapper).find(".datatable").hide();
			$(ssWrapper).find(".datatable:eq("+btnIndex+")").show();
		})
	})
	</script>