        <?php
        /* This piece of shit is a mess. Nuclear, what the fuck where you thinking that numerical array keys makes sense? */
        $highlight = @$view->User->loggedInUser->board_nickname;
        $i=1; foreach($view->board as $board_key => $board_val): ?>
            <div class="chapterinfo">
                <h1 class="chapternumber">Chapter 0<?php echo $i;$i++;?></h1>
                <h1 class="chaptername"><?=$board_key;?></h1>
            </div>
            <div class="chambers">
                <?php foreach($board_val as $chamb_key => $chamb_val): ?>
                    <div class="chamber">
                        <div class="chamberimage" style="background: url('/images/chambers/<?=$chamb_val[0][0];?>.jpg')">
                            <div class="chambertitle">
                                <div class="titlebghelper"></div>
                                <div class="titlebg"><a href="/chamber/<?=$chamb_val[0][0];?>"><?=$chamb_key; ?></a></div>
                                <div class="chamber_icons">
                                    <span class="icons youtube_icon"></span>
                                    <?php if($chamb_val[0][1] == "1"): ?><a href="<?php echo "http://steamcommunity.com/stats/Portal2/leaderboards/".$chamb_val[0][0]; ?>" class="icons steam_icon" target="_blank"></a><?php endif; ?>
                                </div>
                            </div>
                        </div>
                        <div class="chamber_scores">
                            <?php foreach($chamb_val[1] as $pl_key => $pl_val): ?>
                            <?php if($pl_key == 0) { ?>
                            <div class="firstplace">
                                <div class="entry <?php if($highlight == $pl_val[0]) { echo "highlight"; } ?>">
                                    <div class="name"><?=$pl_val[0]?></div>
                                    <div class="score"><?=$pl_val[1]?></div>
                                </div>
                            </div>
                            <div class="othernoobscores">
                                <?php }
                                else {
                                    if($pl_key < 8) {
                                        ?>
                                        <div class="entry <?php if($highlight == $pl_val[0]) { echo "highlight"; } ?>">
                                            <div class="name"><?=$pl_val[0]?></div>
                                            <div class="score"><?=$pl_val[1]?></div>
                                        </div>
                                    <?php } } ?>

                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>