<div id="footer">
    <div class="footerleft">
        <div>Developed, designed and hosted by <a href="/profile/76561198043770492" target="_blank">Nuclear</a></div>
        <div><a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=VESN9DWJ45DCS">Support further development and hosting expenses by donating</a></div>
    </div>
    <div class="footeright">This page was generated in <?php echo microtime(true) - $this->startupTimestamp; ?> seconds</div>
</div>