<?php // DIV inside anchor element is an intergalatic law violation ?>
<a href="/home"><div id="sp_icon" class="nav_icons"></div>SINGLEPLAYER</a>
<a href="/coop"><div id="coop_icon" class="nav_icons"></div>COOPERATIVE</a>
<a href="/changelog"><div id="ch_icon" class="nav_icons"></div>SCORE UPDATES</a>
<a href="/leastportals"><div id="lp_icon" class="nav_icons"></div>LEAST PORTALS</a>
<a href="/singlesegment"><div id="ss_icon" class="nav_icons"></div>SINGLE SEGMENT</a>